/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PokedexImport } from './routes/pokedex'
import { Route as IndexImport } from './routes/index'
import { Route as PokemonNameImport } from './routes/pokemon.$name'

// Create/Update Routes

const PokedexRoute = PokedexImport.update({
  id: '/pokedex',
  path: '/pokedex',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonNameRoute = PokemonNameImport.update({
  id: '/pokemon/$name',
  path: '/pokemon/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pokedex': {
      id: '/pokedex'
      path: '/pokedex'
      fullPath: '/pokedex'
      preLoaderRoute: typeof PokedexImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/$name': {
      id: '/pokemon/$name'
      path: '/pokemon/$name'
      fullPath: '/pokemon/$name'
      preLoaderRoute: typeof PokemonNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokedex': typeof PokedexRoute
  '/pokemon/$name': typeof PokemonNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokedex': typeof PokedexRoute
  '/pokemon/$name': typeof PokemonNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pokedex': typeof PokedexRoute
  '/pokemon/$name': typeof PokemonNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokedex' | '/pokemon/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokedex' | '/pokemon/$name'
  id: '__root__' | '/' | '/pokedex' | '/pokemon/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokedexRoute: typeof PokedexRoute
  PokemonNameRoute: typeof PokemonNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokedexRoute: PokedexRoute,
  PokemonNameRoute: PokemonNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pokedex",
        "/pokemon/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pokedex": {
      "filePath": "pokedex.tsx"
    },
    "/pokemon/$name": {
      "filePath": "pokemon.$name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
